### ISSUE TITLE
ci: publish is not working expected?

### ISSUE THREAD

**Issue by haarchri** [upbound/upjet-provider-template#12]
### What happened?

![image](https://user-images.githubusercontent.com/21083497/198850570-ec7aa1a1-535c-47d7-b0df-4bf86f7eb27c.png)

Epic #

**Comment by haarchri** [comment]
think we can skip it here - and enable for forked projects

**Comment by luebken** [comment]
Related https://github.com/upbound/upjet-provider-template/issues/19

**Comment by luebken** [comment]
e.g. https://github.com/upbound/upjet-provider-template/actions/runs/3428232188/jobs/5712237997
