### ISSUE TITLE
Set CRD root group to organisation uri instead of upbound uri

### ISSUE THREAD

**Issue by sboschman** [upbound/upjet-provider-template#17]
### What happened?

All CRD's are generated with root group 'upbound.io'. To fix this you have to make a few changes. Would be nice if the `./hack/prepare.sh` script would make these changes automatically, especially as step 3 of the docs suggest all upbound references are replaced with your organisation. 

Changes:
1) Define root group for terraform resources in `config/provider.go`:
```
ujconfig.WithRootGroup("github.crossplane.io"),
```

2) Define root group for ProviderConfig, ProviderConfigUsage and StoreConfig:
   - `groupName` annotation in apis/(v1alpha1|v1beta1)/doc.go
   - `Group` constant in apis/(v1alpha1|v1beta1)/register.go

Perhaps the `./hack/prepare.sh` can take an extra input to set the root group, as the organisation input is 'crossplane-contrib' and the root group should end in 'crossplane.io'.

**Comment by luebken** [comment]
Thanks @sboschman for the issue. We think it's as great enhancement.
