### ISSUE TITLE
Dockerfile assumes terraform provider binaries are available from releases.hashicorp.com

### ISSUE THREAD

**Issue by bobh66** [upbound/upjet-provider-template#25]
### What happened?
The Dockerfile assumes that the required terraform provider binaries are available from releases.hashicorp.com:

```
ADD https://releases.hashicorp.com/${TERRAFORM_PROVIDER_DOWNLOAD_NAME}/${TERRAFORM_PROVIDER_VERSION}/${TERRAFORM_PROVIDER_DOWNLOAD_NAME}_${TERRAFORM_PROVIDER_VERSION}_${TARGETOS}_${TARGETARCH}.zip /tmp
```

Many provider binaries are available on github directly from their repositories and are not officially released by Hashicorp.

### How can we reproduce it?
Build a crossplane provider for a terraform provider that does not have it's binaries on releases.hashicorp.com

Given all of the existing configuration options in the Makefile for the target provider:
```
export TERRAFORM_PROVIDER_SOURCE := hashicorp/null
export TERRAFORM_PROVIDER_REPO := https://github.com/hashicorp/terraform-provider-null
export TERRAFORM_PROVIDER_VERSION := 3.1.0
export TERRAFORM_PROVIDER_DOWNLOAD_NAME := terraform-provider-null
export TERRAFORM_NATIVE_PROVIDER_BINARY := terraform-provider-null_v3.1.0_x5
export TERRAFORM_DOCS_PATH := docs/resources
```
adding one more to specify the location of the binaries would be very helpful.

**Comment by haarchri** [comment]
solved with https://github.com/upbound/upjet-provider-template/pull/29/files
