### ISSUE TITLE
Print debug messages using human-readable time format

### ISSUE THREAD

**Issue by bobh66** [upbound/upjet-provider-template#26]
### What problem are you facing?
The time formatting of output messages is not in a human readable format.

### How could Upbound help solve your problem?
Add the ISO8601 or RFC33339 time encoder to the log output formatter

**Comment by bobh66** [comment]
Actually this is handled in the latest release of crossplane-runtime so updating to 0.19 will fix it

**Comment by haarchri** [comment]
@bobh66 we running atm v0.20.0rc candidate for crossplane-runtime so we can close this issue https://github.com/upbound/upjet-provider-template/blob/main/go.mod#L6 - thanks
