### ISSUE TITLE
Generation fails for mrparkers/keycloak with the latest version

### ISSUE THREAD

**Issue by smoehrle** [upbound/upjet-provider-template#32]
### What happened?

I tried to generate a provider for [mrparkers/keycloak](https://registry.terraform.io/providers/mrparkers/keycloak/latest/docs).  But the generation fails with the newest version (f965062) of upjet-provider-template with the following error message:
```
scraper: error: Failed to scrape Terraform provider metadata: cannot scrape Terraform registry: failed to scrape resource metadata from path: ../.work/mrparkers/keycloak/docs/resources/attribute_importer_identity_provider_mapper.md: failed to find the prelude of the document using the xpath expressions: //text()[contains(., "description") and contains(., "page_title")]
```
As far as I understand this error message, it fails because the docs do not contain a description field. See relevant files below for an AWS and a Keycloak example.

Error was probably introduced with the upjet update since 108a029 is still working.

Relevant files:
[terraform-provider-keycloak example](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/docs/resources/attribute_importer_identity_provider_mapper.md)
[terraform-provider-aws example](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/ami.html.markdown)

**Comment by fire-ant** [comment]
@smoehrle its likely failed because there is a. dependency on using the docs based on the upstream terraform provider conforming to the format provided by https://github.com/hashicorp/terraform-plugin-docs. Where the docs deviate it will likely fail.

**Comment by turkenf** [comment]
Hi @smoehrle,

Thank you for raising this issue, could you please replace the docs scraper line(Generate documentation from Terraform docs.) of the apis/generate.go file with the following and run make generate again?
```
//go:generate go run github.com/upbound/upjet/cmd/scraper -n ${TERRAFORM_PROVIDER_SOURCE} -r ../.work/${TERRAFORM_PROVIDER_SOURCE}/${TERRAFORM_DOCS_PATH} -o ../config/provider-metadata.yaml --prelude-xpath "//text()[contains(., \"page_title\")]"
```

**Comment by smoehrle** [comment]
Hey @turkenf 

I could verify that I'm able to generate the provider with your proposed change!

To make it fully work, I also had to make some changes to the terraform provider (see https://github.com/mrparkers/terraform-provider-keycloak/pull/855) since there were 2 files missing even the page_title.

**Comment by haarchri** [comment]
@smoehrle thanks for feedback - we will close this issus
