### ISSUE TITLE
Switch to reusable workflows from the uptest repository

### ISSUE THREAD

**Issue by ulucinar** [upbound/upjet-provider-template#35]
### What problem are you facing?

We are maintaining Github workflows for the official Upbound providers at https://github.com/upbound/uptest/tree/main/.github/workflows as reusable workflows that the provider repositories depend on. Although the provider that this repo produces is not an official provider, I think it may still be possible to replace the workflows in this repo with the reusable ones from https://github.com/upbound/uptest. 

### How could Upbound help solve your problem?

We may consider reusing the provider workflows from https://github.com/upbound/uptest in this repo.

**Comment by haarchri** [comment]
did this for all ci-workflows without ci.yaml in https://github.com/upbound/upjet-provider-template/pull/48
