### ISSUE TITLE
Provision `upbound/upjet-provider-template` package repository

### ISSUE THREAD

**Issue by ulucinar** [upbound/upjet-provider-template#46]
### What problem are you facing?

Currently, when a commit to the `main` branch triggers the pushing of the `upbound/upjet-provider-template` package to `xpkg.upbound.io`, it fails because there's no such package repository:
https://github.com/upbound/upjet-provider-template/actions/workflows/ci.yml

### How could Upbound help solve your problem?

We would like to give some visibility to the `upbound/upjet-provider-template` in Upbound marketplace by provisioning this package repository and publishing these packages in the marketplace. Then we will also need to consider doing releases from this repo. We may also just provision the package repository without publishing the packages in the marketplace (private repo).

Epic #

**Comment by jastang** [comment]
@ulucinar @jeanduplessis will any users be pulling/installing the package? if not, I think it's acceptable to leave the repo publishing policy as manual so we can push/pull freely without exposing a listing page.

**Comment by haarchri** [comment]
no one will consume this package here - lets publish it and set publishing policy to manual - and in cases we want to publish visible we can set it

**Comment by jastang** [comment]
https://marketplace.upbound.io/account/upbound/upjet-provider-template

**Comment by haarchri** [comment]
thanks @jastang  for adding the credentials - pipeline is green
